services:

  db:
    image: postgres:16
    container_name: waluty-db

    environment:
      POSTGRES_DB: waluty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    depends_on:
      - db

  frontend:
    build: ./frontend

    ports:
      - "4200:4200"

    depends_on:
      - backend